version: '3.9'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.9
    container_name: python-app
    restart: unless-stopped
    ports:
      - '3000:5000'
    networks:
      - app-network
  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    volumes:
      - /e/Db:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: